const staff = [
    {
        id: 1,
        firstName: "Иван",
        lastName: "Иванов",
        divisionID: 1,
        role: "начальник",
        birthday: new Date("1980-05-15"),
        startDate: new Date("2010-06-01"),
      },
      {
        id: 2,
        firstName: "Петр",
        lastName: "Петров",
        divisionID: 1,
        role: "инженер",
        birthday: new Date("1985-07-20"),
        startDate: new Date("2012-08-15"),
      },
      {
        id: 3,
        firstName: "Сергей",
        lastName: "Сергеев",
        divisionID: 1,
        role: "сотрудник",
        birthday: new Date("1990-09-25"),
        startDate: new Date("2015-10-10"),
      },
      {
        id: 4,
        firstName: "Алексей",
        lastName: "Алексеев",
        divisionID: 1,
        role: "инспектор",
        birthday: new Date("1982-11-30"),
        startDate: new Date("2011-12-05"),
      },
      {
        id: 5,
        firstName: "Дмитрий",
        lastName: "Дмитриев",
        divisionID: 2,
        role: "начальник",
        birthday: new Date("1978-03-10"),
        startDate: new Date("2009-04-20"),
      },
      {
        id: 6,
        firstName: "Андрей",
        lastName: "Андреев",
        divisionID: 2,
        role: "инженер",
        birthday: new Date("1987-06-15"),
        startDate: new Date("2013-07-25"),
      },
      {
        id: 7,
        firstName: "Николай",
        lastName: "Николаев",
        divisionID: 2,
        role: "сотрудник",
        birthday: new Date("1992-08-20"),
        startDate: new Date("2016-09-30"),
      },
      {
        id: 8,
        firstName: "Владимир",
        lastName: "Владимиров",
        divisionID: 2,
        role: "инспектор",
        birthday: new Date("1984-10-25"),
        startDate: new Date("2010-11-15"),
      },
      {
        id: 9,
        firstName: "Евгений",
        lastName: "Евгеньев",
        divisionID: 3,
        role: "начальник",
        birthday: new Date("1975-12-30"),
        startDate: new Date("2008-01-10"),
      },
      {
        id: 10,
        firstName: "Александр",
        lastName: "Александров",
        divisionID: 3,
        role: "инженер",
        birthday: new Date("1989-02-05"),
        startDate: new Date("2014-03-15"),
      },
      {
        id: 11,
        firstName: "Михаил",
        lastName: "Михайлов",
        divisionID: 3,
        role: "сотрудник",
        birthday: new Date("1991-04-10"),
        startDate: new Date("2017-05-20"),
      },
      {
        id: 12,
        firstName: "Олег",
        lastName: "Олегов",
        divisionID: 3,
        role: "инспектор",
        birthday: new Date("1983-06-15"),
        startDate: new Date("2012-07-25"),
      },
      {
        id: 13,
        firstName: "Виктор",
        lastName: "Викторов",
        divisionID: 4,
        role: "начальник",
        birthday: new Date("1977-08-20"),
        startDate: new Date("2007-09-30"),
      },
      {
        id: 14,
        firstName: "Геннадий",
        lastName: "Геннадьев",
        divisionID: 4,
        role: "инженер",
        birthday: new Date("1986-10-25"),
        startDate: new Date("2011-11-15"),
      },
      {
        id: 15,
        firstName: "Павел",
        lastName: "Павлов",
        divisionID: 4,
        role: "сотрудник",
        birthday: new Date("1993-12-30"),
        startDate: new Date("2018-01-10"),
      },
      {
        id: 16,
        firstName: "Константин",
        lastName: "Константинов",
        divisionID: 4,
        role: "инспектор",
        birthday: new Date("1981-02-05"),
        startDate: new Date("2010-03-15"),
      },
      {
        id: 17,
        firstName: "Станислав",
        lastName: "Станиславов",
        divisionID: 5,
        role: "начальник",
        birthday: new Date("1976-04-10"),
        startDate: new Date("2006-05-20"),
      },
      {
        id: 18,
        firstName: "Артем",
        lastName: "Артемов",
        divisionID: 5,
        role: "инженер",
        birthday: new Date("1988-06-15"),
        startDate: new Date("2013-07-25"),
      },
      {
        id: 19,
        firstName: "Юрий",
        lastName: "Юрьев",
        divisionID: 5,
        role: "сотрудник",
        birthday: new Date("1994-08-20"),
        startDate: new Date("2019-09-30"),
      },
      {
        id: 20,
        firstName: "Валерий",
        lastName: "Валериев",
        divisionID: 5,
        role: "инспектор",
        birthday: new Date("1980-10-25"),
        startDate: new Date("2009-11-15"),
      },
      {
        id: 21,
        firstName: "Семен",
        lastName: "Семенов",
        divisionID: 6,
        role: "начальник",
        birthday: new Date("1974-12-30"),
        startDate: new Date("2005-01-10"),
      },
      {
        id: 22,
        firstName: "Федор",
        lastName: "Федоров",
        divisionID: 6,
        role: "инженер",
        birthday: new Date("1987-02-05"),
        startDate: new Date("2012-03-15"),
      },
      {
        id: 23,
        firstName: "Григорий",
        lastName: "Григорьев",
        divisionID: 6,
        role: "сотрудник",
        birthday: new Date("1995-04-10"),
        startDate: new Date("2020-05-20"),
      },
      {
        id: 24,
        firstName: "Борис",
        lastName: "Борисов",
        divisionID: 6,
        role: "инспектор",
        birthday: new Date("1982-06-15"),
        startDate: new Date("2011-07-25"),
      },
      {
        id: 25,
        firstName: "Роман",
        lastName: "Романов",
        divisionID: 7,
        role: "начальник",
        birthday: new Date("1973-08-20"),
        startDate: new Date("2004-09-30"),
      },
      {
        id: 26,
        firstName: "Тимур",
        lastName: "Тимуров",
        divisionID: 7,
        role: "инженер",
        birthday: new Date("1989-10-25"),
        startDate: new Date("2014-11-15"),
      },
      {
        id: 27,
        firstName: "Даниил",
        lastName: "Даниилов",
        divisionID: 7,
        role: "сотрудник",
        birthday: new Date("1996-12-30"),
        startDate: new Date("2021-01-10"),
      },
      {
        id: 28,
        firstName: "Игорь",
        lastName: "Игорев",
        divisionID: 7,
        role: "инспектор",
        birthday: new Date("1981-02-05"),
        startDate: new Date("2010-03-15"),
      },
      {
        id: 29,
        firstName: "Леонид",
        lastName: "Леонидов",
        divisionID: 8,
        role: "начальник",
        birthday: new Date("1972-04-10"),
        startDate: new Date("2003-05-20"),
      },
      {
        id: 30,
        firstName: "Вадим",
        lastName: "Вадимов",
        divisionID: 8,
        role: "инженер",
        birthday: new Date("1988-06-15"),
        startDate: new Date("2013-07-25"),
      },
      {
        id: 31,
        firstName: "Максим",
        lastName: "Максимов",
        divisionID: 8,
        role: "сотрудник",
        birthday: new Date("1997-08-20"),
        startDate: new Date("2022-09-30"),
      },
      {
        id: 32,
        firstName: "Арсений",
        lastName: "Арсеньев",
        divisionID: 8,
        role: "инспектор",
        birthday: new Date("1983-10-25"),
        startDate: new Date("2012-11-15"),
      },
      {
        id: 33,
        firstName: "Кирилл",
        lastName: "Кириллов",
        divisionID: 9,
        role: "начальник",
        birthday: new Date("1971-12-30"),
        startDate: new Date("2002-01-10"),
      },
      {
        id: 34,
        firstName: "Вячеслав",
        lastName: "Вячеславов",
        divisionID: 9,
        role: "инженер",
        birthday: new Date("1987-02-05"),
        startDate: new Date("2012-03-15"),
      },
      {
        id: 35,
        firstName: "Глеб",
        lastName: "Глебов",
        divisionID: 9,
        role: "сотрудник",
        birthday: new Date("1998-04-10"),
        startDate: new Date("2023-05-20"),
      },
      {
        id: 36,
        firstName: "Денис",
        lastName: "Денисов",
        divisionID: 9,
        role: "инспектор",
        birthday: new Date("1984-06-15"),
        startDate: new Date("2013-07-25"),
      },
      {
        id: 37,
        firstName: "Егор",
        lastName: "Егоров",
        divisionID: 10,
        role: "начальник",
        birthday: new Date("1970-08-20"),
        startDate: new Date("2001-09-30"),
      },
      {
        id: 38,
        firstName: "Захар",
        lastName: "Захаров",
        divisionID: 10,
        role: "инженер",
        birthday: new Date("1986-10-25"),
        startDate: new Date("2011-11-15"),
      },
      {
        id: 39,
        firstName: "Илья",
        lastName: "Ильин",
        divisionID: 10,
        role: "сотрудник",
        birthday: new Date("1999-12-30"),
        startDate: new Date("2024-01-10"),
      },
      {
        id: 40,
        firstName: "Лев",
        lastName: "Львов",
        divisionID: 10,
        role: "инспектор",
        birthday: new Date("1985-02-05"),
        startDate: new Date("2014-03-15"),
      },
      {
        id: 41,
        firstName: "Матвей",
        lastName: "Матвеев",
        divisionID: 11,
        role: "начальник",
        birthday: new Date("1969-04-10"),
        startDate: new Date("2000-05-20"),
      },
      {
        id: 42,
        firstName: "Никита",
        lastName: "Никитин",
        divisionID: 11,
        role: "инженер",
        birthday: new Date("1985-06-15"),
        startDate: new Date("2010-07-25"),
      },
      {
        id: 43,
        firstName: "Олег",
        lastName: "Олегов",
        divisionID: 11,
        role: "сотрудник",
        birthday: new Date("2000-08-20"),
        startDate: new Date("2023-09-30"),
      },
      {
        id: 44,
        firstName: "Петр",
        lastName: "Петров",
        divisionID: 11,
        role: "инспектор",
        birthday: new Date("1986-10-25"),
        startDate: new Date("2011-11-15"),
      },
      {
        id: 45,
        firstName: "Руслан",
        lastName: "Русланов",
        divisionID: 12,
        role: "начальник",
        birthday: new Date("1968-12-30"),
        startDate: new Date("1999-01-10"),
      },
      {
        id: 46,
        firstName: "Святослав",
        lastName: "Святославов",
        divisionID: 12,
        role: "инженер",
        birthday: new Date("1984-02-05"),
        startDate: new Date("2009-03-15"),
      },
      {
        id: 47,
        firstName: "Тимофей",
        lastName: "Тимофеев",
        divisionID: 12,
        role: "сотрудник",
        birthday: new Date("2001-04-10"),
        startDate: new Date("2024-05-20"),
      },
      {
        id: 48,
        firstName: "Филипп",
        lastName: "Филиппов",
        divisionID: 12,
        role: "инспектор",
        birthday: new Date("1987-06-15"),
        startDate: new Date("2012-07-25"),
      },
      {
        id: 49,
        firstName: "Эдуард",
        lastName: "Эдуардов",
        divisionID: 1,
        role: "инженер",
        birthday: new Date("1989-08-20"),
        startDate: new Date("2014-09-30"),
      },
      {
        id: 50,
        firstName: "Ярослав",
        lastName: "Ярославов",
        divisionID: 1,
        role: "сотрудник",
        birthday: new Date("2002-10-25"),
        startDate: new Date("2017-11-15"),
      },
      {
        id: 51,
        firstName: "Антон",
        lastName: "Антонов",
        divisionID: 2,
        role: "инженер",
        birthday: new Date("1988-12-30"),
        startDate: new Date("2013-01-10"),
      },
      {
        id: 52,
        firstName: "Богдан",
        lastName: "Богданов",
        divisionID: 2,
        role: "сотрудник",
        birthday: new Date("2003-02-05"),
        startDate: new Date("2018-03-15"),
      },
      {
        id: 53,
        firstName: "Виталий",
        lastName: "Витальев",
        divisionID: 3,
        role: "инженер",
        birthday: new Date("1987-04-10"),
        startDate: new Date("2012-05-20"),
      },
      {
        id: 54,
        firstName: "Герман",
        lastName: "Германов",
        divisionID: 3,
        role: "сотрудник",
        birthday: new Date("2004-06-15"),
        startDate: new Date("2019-07-25"),
      },
      {
        id: 55,
        firstName: "Демьян",
        lastName: "Демьянов",
        divisionID: 4,
        role: "инженер",
        birthday: new Date("1986-08-20"),
        startDate: new Date("2011-09-30"),
      },
      {
        id: 56,
        firstName: "Евгений",
        lastName: "Евгеньев",
        divisionID: 4,
        role: "сотрудник",
        birthday: new Date("2005-10-25"),
        startDate: new Date("2030-11-15"),
      },
      {
        id: 57,
        firstName: "Ждан",
        lastName: "Жданов",
        divisionID: 5,
        role: "инженер",
        birthday: new Date("1985-12-30"),
        startDate: new Date("2010-01-10"),
      },
      {
        id: 58,
        firstName: "Зиновий",
        lastName: "Зиновьев",
        divisionID: 5,
        role: "сотрудник",
        birthday: new Date("2006-02-05"),
        startDate: new Date("2031-03-15"),
      },
];

module.exports = staff;